'use client';
import { useState } from 'react';
import {useDialog} from '@/app/lib/conversation/useDialog';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/app/providers/AuthProvider';
import { Header } from '@/app/components/simulation/Workspace';
export default function Home(){
 const {signIn,isAuthenticated,isManager}=useAuth();const router=useRouter();
 const [login,setLogin]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useDialog(login,()=>setLogin(false));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);router.push('/simulation');}catch(err){setError(err instanceof Error?err.message:'Connexion impossible.');}finally{setBusy(false);}};
 return <div className="yg-shell"><Header right={<>{isAuthenticated&&isManager&&<Link href="/studio">Studio pédagogique</Link>}<button onClick={()=>isAuthenticated?router.push('/simulation'):setLogin(true)}>{isAuthenticated?'Mon espace':'Se connecter'} ↗</button></>}/><main className="yg-landing"><div className="yg-landing-copy"><div className="yg-eyebrow"><span className="yg-live-dot"/> L’EXPÉRIENCE FAIT LA DIFFÉRENCE</div><h1>Les bons échanges<br/>ne s’improvisent pas.<br/><em>Ils se pratiquent.</em></h1><p className="yg-lead">Entrez dans la conversation. Écoutez, questionnez,<br className="yg-desktop"/> découvrez ce qui compte vraiment pour votre client.</p><button className="yg-button" onClick={()=>isAuthenticated?router.push('/simulation'):setLogin(true)}>Entrer dans mon espace <span>↗</span></button><p className="yg-small yg-landing-note">Un interlocuteur virtuel. Une expérience bien réelle.</p><div className="yg-landing-proof"><span>01 <strong>Échangez</strong></span><span>02 <strong>Prenez du recul</strong></span><span>03 <strong>Progressez</strong></span></div></div><div className="yg-landing-art"><div className="yg-art-circle yg-art-circle-one"/><div className="yg-art-circle yg-art-circle-two"/><div className="yg-art-line"/><div className="yg-art-caption">LAISSEZ PLACE<br/>À LA <em>conversation.</em></div><div className="yg-art-dialogue"><span>VOUS</span><p>« Qu’est-ce qui est<br/>le plus important pour vous ? »</p><div className="yg-wave">{Array.from({length:22},(_,i)=><i key={i} style={{height:8+Math.sin(i*.9)**2*25,animationDelay:`${i*70}ms`}}/>)}</div></div><span className="yg-art-foot">ÉCOUTER EST DÉJÀ UN PREMIER PAS.</span></div></main><footer className="yg-footer"><span>YouGotIt · L’aisance se travaille.</span><span>Conçu pour apprendre, avec confiance.</span></footer>{login&&<div className="yg-modal-backdrop" onClick={()=>setLogin(false)}><section className="yg-modal" role="dialog" aria-modal="true" aria-labelledby="login-title" onClick={e=>e.stopPropagation()}><button className="yg-close" onClick={()=>setLogin(false)}>Fermer ×</button><span className="yg-kicker">BIENVENUE DANS VOTRE ESPACE</span><h2 id="login-title">À vous de jouer.</h2><p>Retrouvez les accès transmis par votre formateur.</p><form onSubmit={submit}><label className="yg-field">Adresse e-mail<input autoFocus type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="yg-field">Mot de passe<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="yg-error" role="alert">{error}</p>}<button className="yg-button" disabled={busy}>{busy?'Connexion…':'Retrouver mon espace'} ↗</button></form></section></div>}</div>;
}
