import { createClient } from "@/app/lib/supabase/server";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const supabase = await createClient();

  // Check auth
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: "Non authentifié" }, { status: 401 });
  }

  // Check role
  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (!profile || profile.role !== "manager") {
    return NextResponse.json({ error: "Accès réservé aux managers" }, { status: 403 });
  }

  // Parse multipart form data
  const formData = await request.formData();
  const title = formData.get("title") as string;
  const description = formData.get("description") as string | null;
  const documentText = formData.get("documentText") as string;
  const file = formData.get("file") as File | null;

  if (!title || !documentText) {
    return NextResponse.json({ error: "Titre et contenu du document requis" }, { status: 400 });
  }

  // Upload file to Storage (best-effort — training works without it)
  let documentPath: string | null = null;
  let documentFilename = "document.txt";

  if (file) {
    documentFilename = file.name;
    const filePath = `${user.id}/${crypto.randomUUID()}-${file.name}`;

    // Convert File to ArrayBuffer for storage upload
    const fileBuffer = await file.arrayBuffer();
    const { error: uploadError } = await supabase.storage
      .from("training-documents")
      .upload(filePath, fileBuffer, {
        contentType: file.type || "application/octet-stream",
        upsert: false,
      });

    if (uploadError) {
      console.error("[trainings/create] Storage upload error (non-blocking):", uploadError.message);
      // Continue without storage — the document_text is what matters
    } else {
      documentPath = filePath;
    }
  }

  // Create training (join_code auto-generated by DB trigger)
  const { data: training, error: createError } = await supabase
    .from("trainings")
    .insert({
      manager_id: user.id,
      title,
      description: description || null,
      document_filename: documentFilename,
      document_path: documentPath,
      document_text: documentText,
      status: "draft",
    })
    .select()
    .single();

  if (createError) {
    console.error("[trainings/create] DB insert error:", createError.message, createError.details, createError.hint);
    return NextResponse.json({ error: "Échec de la création de la formation. Veuillez réessayer." }, { status: 500 });
  }

  return NextResponse.json({ training });
}
